# Change these first
owner: Taigacraft34 # Your GitHub organization or username, where this repository lives
repo: status-gc # The name of this repository

sites:
  - name: Greencraft
    url: https://greencraft.fr
  - name: Minecraft
    check: "tcp-ping"
    url: play.greencraft.fr
    port: 8236

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: gcstatus.openvanilla.fr
  # baseUrl: /status-gc
  logoUrl: https://greencraft.fr/storage/img/logo.png
  name: Greencraft Status
  introTitle: "Page de Status de **Greencraft**"
  introMessage: Bienvenue sur la page de status !
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://greencraft.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
